kind: pipeline
type: docker
name: compile

steps:
- name: test
  image: maven
  commands:
  - mvn test
- name: build
  image: maven
  commands:
  - mvn package
- name: deploy
  image: plugins/docker
  settings:
    repo: docker.durkin.app/erasure
    registry: docker.durkin.app
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
